# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37629917873293d28abc9a944e97039c38f3eb30123affbfd7f9c7439cd003adf523a49ad909007d2555a8f87f98a838ffedbb8a95a1d5f558bab45ae8b20896

test:
  secret_key_base: 66b5feba9bc85ab92d2676eee354904c31bbba0cbdb9c537af7b95111ff3eaa2a261d0c619e2224984fd67259d1c5ad51e65a03a2620f218dbef2ebc5fb53798

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
